# Generated by Django 3.2.19 on 2023-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter_pickers', '0003_alter_event_borough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='borough',
            field=models.CharField(choices=[('BAD', 'Barking and Dagenham'), ('BAR', 'Barnet'), ('BEX', 'Bexley'), ('BRE', 'Brent'), ('BRO', 'Bromley'), ('CAM', 'Camden'), ('CRO', 'Croydon'), ('EAL', 'Ealing'), ('ENF', 'Enfield'), ('GRE', 'Greenwich'), ('HAC', 'Hackney'), ('HAF', 'Hammersmith and Fulham'), ('HAR', 'Haringey'), ('HRW', 'Harrow'), ('HAV', 'Havering'), ('HIL', 'Hillingdon'), ('HOU', 'Hounslow'), ('ISL', 'Islington'), ('KAC', 'Kensington and Chelsea'), ('KIN', 'Kingston'), ('LAM', 'Lambeth'), ('LEW', 'Lewisham'), ('MER', 'Merton'), ('NEW', 'Newham'), ('RED', 'Redbridge'), ('RIC', 'Richmond'), ('SOU', 'Southwark'), ('SUT', 'Sutton'), ('TOW', 'Tower Hamlets'), ('WAL', 'Waltham Forest'), ('WAN', 'Wandsworth'), ('WES', 'Westminster')], max_length=80),
        ),
    ]
